package codegen

import (
	"strings"
	"testing"

	"github.com/smm-h/pgdesign/internal/model"
)

func TestParsePrivacyCheck(t *testing.T) {
	tests := []struct {
		name     string
		expr     string
		wantNil  bool
		wantLook string
		wantFlag string
	}{
		{
			name:     "chat_enabled with sender_id",
			expr:     "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
			wantLook: "sender_id",
			wantFlag: "chat_enabled",
		},
		{
			name:     "friends_enabled with followed_id",
			expr:     "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
			wantLook: "followed_id",
			wantFlag: "friends_enabled",
		},
		{
			name:     "qualified table reference",
			expr:     "player_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = game_comment.player_id AND chat_enabled = true)",
			wantLook: "player_id",
			wantFlag: "chat_enabled",
		},
		{
			name:    "no privacy reference",
			expr:    "player_id::text = current_setting('app.player_id')",
			wantNil: true,
		},
		{
			name:    "read all",
			expr:    "true",
			wantNil: true,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			result := parsePrivacyCheck(tt.expr)
			if tt.wantNil {
				if result != nil {
					t.Errorf("expected nil, got %+v", result)
				}
				return
			}
			if result == nil {
				t.Fatal("expected non-nil result")
			}
			if result.lookupColumn != tt.wantLook {
				t.Errorf("lookupColumn: expected %q, got %q", tt.wantLook, result.lookupColumn)
			}
			if result.flagColumn != tt.wantFlag {
				t.Errorf("flagColumn: expected %q, got %q", tt.wantFlag, result.flagColumn)
			}
		})
	}
}

func TestPythonGenerator_Generate(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "chat_messages",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:      "chat_read_all",
						Operation: "SELECT",
						Using:     "true",
					},
					{
						Name:         "chat_requires_enabled",
						Operation:    "INSERT",
						WithCheck:    "sender_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = sender_id AND chat_enabled = true)",
						ErrorCode:    "chat_disabled",
						ErrorMessage: "Chat is disabled in your privacy settings",
					},
				},
			},
			{
				Name:   "follow",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "follow_requires_friends_enabled",
						Operation:    "INSERT",
						WithCheck:    "follower_id::text = current_setting('app.player_id') AND EXISTS (SELECT 1 FROM game.player_privacy_settings WHERE player_id = followed_id AND friends_enabled = true)",
						ErrorCode:    "target_friends_disabled",
						ErrorMessage: "This player has disabled friend/follow requests",
					},
				},
			},
		},
	}

	gen := &PythonGenerator{}
	out, err := gen.Generate(schema)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	result := string(out)

	// Header checks.
	if !strings.Contains(result, "# Generated by pgdesign codegen") {
		t.Error("missing header comment")
	}
	if !strings.Contains(result, "class PolicyResult:") {
		t.Error("missing PolicyResult dataclass")
	}
	if !strings.Contains(result, "from dataclasses import dataclass") {
		t.Error("missing dataclass import")
	}

	// chat_requires_enabled validator.
	if !strings.Contains(result, "async def check_chat_requires_enabled(conn, sender_id: str) -> PolicyResult:") {
		t.Error("missing chat_requires_enabled function signature")
	}
	if !strings.Contains(result, "SELECT chat_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing chat_enabled query")
	}
	if !strings.Contains(result, `code="chat_disabled"`) {
		t.Error("missing chat_disabled error code")
	}

	// follow_requires_friends_enabled validator.
	if !strings.Contains(result, "async def check_follow_requires_friends_enabled(conn, followed_id: str) -> PolicyResult:") {
		t.Error("missing follow_requires_friends_enabled function signature")
	}
	if !strings.Contains(result, "SELECT friends_enabled FROM game.player_privacy_settings WHERE player_id = $1") {
		t.Error("missing friends_enabled query")
	}
	if !strings.Contains(result, `code="target_friends_disabled"`) {
		t.Error("missing target_friends_disabled error code")
	}

	// Should NOT contain the read_all policy (no error code).
	if strings.Contains(result, "check_chat_read_all") {
		t.Error("should not generate validator for read_all policy")
	}
}

func TestPythonGenerator_NoPolicies(t *testing.T) {
	schema := &model.Schema{
		Name: "empty",
		Tables: []model.Table{
			{
				Name:   "items",
				Schema: "empty",
			},
		},
	}

	gen := &PythonGenerator{}
	out, err := gen.Generate(schema)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	result := string(out)
	if !strings.Contains(result, "No generatable policies found") {
		t.Error("expected 'no generatable policies' message")
	}
}

func TestPythonGenerator_UnparsableExpression(t *testing.T) {
	schema := &model.Schema{
		Name: "game",
		Tables: []model.Table{
			{
				Name:   "exotic",
				Schema: "game",
				Policies: []model.Policy{
					{
						Name:         "exotic_policy",
						Operation:    "INSERT",
						WithCheck:    "some_complex_expression(player_privacy_settings)",
						ErrorCode:    "exotic_error",
						ErrorMessage: "Exotic failure",
					},
				},
			},
		},
	}

	gen := &PythonGenerator{}
	out, err := gen.Generate(schema)
	if err != nil {
		t.Fatalf("Generate failed: %v", err)
	}

	result := string(out)
	if !strings.Contains(result, "Skipped exotic_policy") {
		t.Error("expected skip comment for unparsable policy")
	}
}
