package codegen

import (
	"bytes"
	"fmt"
	"regexp"
	"strings"

	"github.com/smm-h/pgdesign/internal/model"
)

// PythonGenerator generates Python async validator functions for RLS policies.
type PythonGenerator struct{}

// privacyCheck describes a parsed reference to player_privacy_settings.
type privacyCheck struct {
	// lookupColumn is the column in the policy table whose value is used to
	// look up the privacy row (e.g. "sender_id", "followed_id", "player_id").
	lookupColumn string
	// flagColumn is the boolean column checked in player_privacy_settings
	// (e.g. "chat_enabled", "friends_enabled").
	flagColumn string
}

// parsePrivacyCheck extracts the privacy settings reference from a policy
// expression. It looks for the pattern:
//
//	EXISTS (SELECT 1 FROM <schema>.player_privacy_settings WHERE player_id = <col> AND <flag> = true)
//
// Returns nil if the expression doesn't match.
func parsePrivacyCheck(expr string) *privacyCheck {
	// Match: player_id = <something> AND <flag_column> = true
	// The <something> can be a bare column name, or a qualified name like game_comment.player_id.
	re := regexp.MustCompile(
		`player_privacy_settings\s+WHERE\s+player_id\s*=\s*(?:[a-z_]+\.)?([a-z_]+)\s+AND\s+([a-z_]+)\s*=\s*true`,
	)
	m := re.FindStringSubmatch(expr)
	if m == nil {
		return nil
	}
	return &privacyCheck{
		lookupColumn: m[1],
		flagColumn:   m[2],
	}
}

// Generate produces a Python file with async validator functions for all
// eligible policies in the schema.
func (g *PythonGenerator) Generate(schema *model.Schema) ([]byte, error) {
	all := ExtractPolicies(schema)
	generatable := FilterGeneratable(all)

	if len(generatable) == 0 {
		return []byte(pythonHeader(schema.Name) + "\n# No generatable policies found.\n"), nil
	}

	var buf bytes.Buffer
	buf.WriteString(pythonHeader(schema.Name))

	for i, pol := range generatable {
		expr := pol.WithCheck
		if expr == "" {
			expr = pol.Using
		}

		check := parsePrivacyCheck(expr)
		if check == nil {
			buf.WriteString(fmt.Sprintf(
				"\n# Skipped %s: could not parse privacy check from expression\n",
				pol.PolicyName,
			))
			continue
		}

		if i > 0 {
			buf.WriteString("\n")
		}

		// Determine the function parameter name from the lookup column.
		// If the lookup column is "player_id", the caller already has it.
		// Otherwise, the lookup column IS the parameter (e.g. "sender_id", "followed_id").
		paramName := check.lookupColumn

		buf.WriteString(fmt.Sprintf(
			"\nasync def check_%s(conn, %s: str) -> PolicyResult:\n",
			pol.PolicyName, paramName,
		))
		buf.WriteString(fmt.Sprintf(
			"    \"\"\"%s\"\"\"\n", pol.ErrorMessage,
		))

		// Generate the query. Use the schema name if present.
		tableFQN := "player_privacy_settings"
		if pol.SchemaName != "" {
			tableFQN = pol.SchemaName + ".player_privacy_settings"
		}

		buf.WriteString(fmt.Sprintf(
			"    row = await conn.fetchrow(\n"+
				"        \"SELECT %s FROM %s WHERE player_id = $1\",\n"+
				"        %s,\n"+
				"    )\n",
			check.flagColumn, tableFQN, paramName,
		))
		buf.WriteString(fmt.Sprintf(
			"    if not row or not row[\"%s\"]:\n"+
				"        return PolicyResult(ok=False, code=%q, message=%q)\n"+
				"    return PolicyResult(ok=True, code=\"\", message=\"\")\n",
			check.flagColumn, pol.ErrorCode, pol.ErrorMessage,
		))
	}

	return buf.Bytes(), nil
}

// pythonHeader returns the standard header for generated Python files.
func pythonHeader(schemaName string) string {
	var sb strings.Builder
	sb.WriteString("# Generated by pgdesign codegen -- do not edit\n")
	if schemaName != "" {
		sb.WriteString(fmt.Sprintf("# Schema: %s\n", schemaName))
	}
	sb.WriteString(`
from __future__ import annotations

from dataclasses import dataclass


@dataclass(frozen=True, slots=True)
class PolicyResult:
    """Result of a policy pre-check."""

    ok: bool
    code: str = ""
    message: str = ""
`)
	return sb.String()
}
